src/menus/urls.py
from django.urls import path, include, re_path

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    re_path(r'^create/$', ItemCreateView.as_view(), name='create'),
    re_path(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    #re_path(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    re_path(r'^$', ItemListView.as_view(), name='list')
]

src/profiles/urls.py
from django.urls import path, include, re_path
from .views import ProfileDetailView

urlpatterns = [
    re_path(r"^(?P<username>[\w-]+)/$", ProfileDetailView.as_view(), name="detail")
    
]

src/menus/models.py
from django.conf import settings
from django.db import models
from restaurants.models import RestaurantLocation
from django.urls import reverse
# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(RestaurantLocation, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    contents = models.TextField(help_text='Separate each item by comma')
    excludes = models.TextField(blank=True, null=True)
    public = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")
 
    def get_excludes(self):
        return self.excludes.split(",")

src/profiles/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
# Create your models here.
User = settings.AUTH_USER_MODEL

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField(User, related_name='is_following', blank=True)
    activated = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user=instance)
        default_user_profile = Profile.objects.get_or_create(user__id=1)[0]
        default_user_profile.followers.add(instance)

post_save.connect(post_save_user_receiver, sender=User)

src/profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, View
from django.http import Http404
from restaurants.models import RestaurantLocation
from menus.models import Item
# Create your views here.
User = get_user_model()

class ProfileFollowToggle(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user_to_toggle = request.POST.get("username")
        return redirect("/u/shaggynick333/")

class ProfileDetailView(DetailView):
    template_name = 'profiles/user.html'
    def get_object(self):
        username = self.kwargs.get("username")
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)
        user = context['user']
        query = self.request.GET.get('q')
        item_exists = Item.objects.filter(user=user).exists()
        query_set = RestaurantLocation.objects.filter(owner=user).search(query)
        if item_exists and query_set.exists():
            context["locations"] = query_set
        return context
    

src/profiles/templates/profiles/user.html
{% extends "base.html" %}
<title>{% block head_title %} {{user.username}} | {{block.super}}{% endblock head_title %}</title>
{% block content %}
<h3>{{ user.username }}</h3>
<p>{% include 'profiles/snippet/follow_form.html' with username=user.username %}</p>
<hr/>
{% if user.item_set.all.exists %}
<form class='form' method='GET' action='.'>
<input type='text' placeholder='Search' name='q' value='{{ request.GET.q }}'>
<button class='btn btn-default' type='submit'>Search</button>
{% if locations %}
{% for rest in locations %}
<div class='row'>
    <div class='col-sm-12'>
        <div class='card card-default' style='margin: 10px;'>
            <h3><b>{{ rest.title }}</b></h3>
            <p>{{ rest.location }} | {{ rest.category }}</p>
            <ol>
                {% for item in rest.item_set.all %}
                <div style='margin-bottom: 15px;'><b>{{ item.name }}</b><br/>
                        {% for ing in item.get_contents %}
                            <span style='padding: 2px 4px;'>{{ ing }}</span>
                        {% endfor %}
                </div>
                {% endfor %}
            </ol>
            
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p class='lead'>No Items Found</p>
{% endif %}
{% endif %}
{% endblock %}