src/menus/urls.py
from django.urls import path, include, re_path

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    re_path(r'^create/$', ItemCreateView.as_view(), name='create'),
    re_path(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    #re_path(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    re_path(r'^$', ItemListView.as_view(), name='list')
]

src/roastery/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView
from profiles.views import ProfileFollowToggle
from restaurants.views import (
RestaurantListView,
RestaurantDetailView,
RestaurantCreateView,
RestaurantUpdateView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    re_path(r'^restaurants/$', RestaurantListView.as_view(), name='restaurants'),
    re_path(r'^restaurants/create/$', RestaurantCreateView.as_view(), name='restaurant-create'),
    re_path(r'^items/', include(('menus.urls', 'menus'), namespace='menus')),
    re_path(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='restaurant-detail'),
    re_path(r'^u/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    re_path(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    re_path(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    re_path(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow')
]

src/menus/models.py
from django.conf import settings
from django.db import models
from restaurants.models import RestaurantLocation
from django.urls import reverse
# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(RestaurantLocation, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    contents = models.TextField(help_text='Separate each item by comma')
    excludes = models.TextField(blank=True, null=True)
    public = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")
 
    def get_excludes(self):
        return self.excludes.split(",")

src/menus/forms.py
from django import forms
from .models import Item
from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'name',
            'restaurant',
            'contents',
            'excludes',
            'public'
        ]

    def __init__(self, user=None, *args, **kwargs):
        print(user)
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

src/menus/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from .models import Item
from .forms import ItemForm
# Create your views here.

class ItemListView(ListView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)
    
class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = ItemForm
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context["title"] = 'Create Item'
        return context

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)
    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context["title"] = 'Update Item'
        return context
    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class ItemDetailView(DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

src/menus/templates/menus/detail-update.html
{% extends "base.html" %}
<title>{% block head_title %}{{ form.instance.name }} | Menu Items | {{block.super}}{% endblock head_title %}</title>
{% block content %}
<h3>{{ form.instance.name }}</h3>
<h4>Location : {{ form.instance.restaurant.name }}</h4>
<ul>
    Contents
    <ul>
        {% for item in form.instance.get_contents %}
        <li>{{ item }}</li>
        {% endfor %}
    </ul>
    {% if form.instance.excludes %}
    Excludes
    <ul>
        {% for item in form.instance.get_excludes %}
        <li>{{ item }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <h4>Make Changes</h4>
    {% include 'snippets/form-snippet.html' %}
</ul>
{% endblock %}

src/menus/templates/menus/item_detail.html
{% extends "base.html" %}
<title>{% block head_title %}Menu Items | {{block.super}}{% endblock head_title %}</title>
{% block content %}
<h3>{{ object.name }}</h3>
<h4>Location : {{ object.restaurant.name }}</h4>
<ul>
    Contents
    <ul>
        {% for item in object.get_contents %}
        <li>{{ item }}</li>
        {% endfor %}
    </ul>
    {% if object.excludes %}
    Excludes
    <ul>
        {% for item in object.get_excludes %}
        <li>{{ item }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</ul>
{% endblock %}

src/menus/templates/menus/item_list.html
{% extends "base.html" %}
<title>{% block head_title %}Menu Items | {{block.super}}{% endblock head_title %}</title>
{% block content %}
<h3>Menu Items <small><a href='{% url "menus:create" %}'>Add</a></small></h3>

<ul>
  {% for obj in object_list %}
  <li><a href="{{ obj.get_absolute_url }}">{{obj.name}}</a><br/>
    {% if obj.contents %}
    Contents
    <ul>
        {% for item in obj.get_contents %}
        <li>{{ item }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% if obj.excludes %}
    Excludes
    <ul>
        {% for item in obj.get_excludes %}
        <li>{{ item }}</li>
        {% endfor %}
    </ul>
    {% endif %}
  {% endfor %}
</ul>
{% endblock %}