src/menus/urls.py
from django.urls import path, include, re_path

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    re_path(r'^create/$', ItemCreateView.as_view(), name='create'),
    re_path(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    #re_path(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    re_path(r'^$', ItemListView.as_view(), name='list')
]

src/roastery/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView
from profiles.views import ProfileFollowToggle
from restaurants.views import (
RestaurantListView,
RestaurantDetailView,
RestaurantCreateView,
RestaurantUpdateView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    re_path(r'^restaurants/$', RestaurantListView.as_view(), name='restaurants'),
    re_path(r'^restaurants/create/$', RestaurantCreateView.as_view(), name='restaurant-create'),
    re_path(r'^items/', include(('menus.urls', 'menus'), namespace='menus')),
    re_path(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='restaurant-detail'),
    re_path(r'^u/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    re_path(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    re_path(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    re_path(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow')
]

src/templates/snippets/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

src/templates/snippets/form-snippet.html
{% if form.errors %}
{{ form.errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
    {{ form.as_table }}
    <button type='submit'>SAVE</button>
</form>

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

src/templates/snippets/nav.html
<div class="container">
<h1>Unchained.com</h1>
<a href="{% url 'home' %}">Home</a>
{% if request.user.is_authenticated %}
<a href="{% url 'restaurants' %}">Restaurants</a>
<a href="{% url 'menus:list' %}">Menu Items</a>
{% endif %}
<a href="{% url 'about' %}">About</a>
<a href="{% url 'contact' %}">Contact</a>
</div>

src/templates/snippets/sidebar.html
<ul>
  <li>Item X</li>
  <li>Item XS</li>
  <li>Item XR</li>
</ul>